services:
  mangarr:
    container_name: mangarr
    image: ghcr.io/nuxencs/mangarr
    restart: unless-stopped
    user: ${PUID}:${PGID} #UID and GID
    environment:
      - MANGARR__DOWNLOAD_LOCATION=
      - MANGARR__NAMING_TEMPLATE=
      - MANGARR__CHECK_INTERVAL=
      - MANGARR__LOG_LEVEL=
      - MANGARR__LOG_PATH=
      - MANGARR__LOG_MAX_SIZE=
      - MANGARR__LOG_MAX_BACKUPS=
    volumes:
      - ${DOCKERCONFDIR}/mangarr:/config # location of the config file
      - /path/to/directory:/path/to/directory # location where you want to save your downloads to