services:
  mangarr:
    container_name: mangarr
    image: ghcr.io/nuxencs/mangarr:latest
    restart: unless-stopped
    user: "${PUID:-65534}:${PGID:-65534}"
    environment:
      MANGARR__DOWNLOAD_LOCATION: /downloads
    volumes:
      - "${DOCKERCONFDIR:-./config}/mangarr:/config"
      - "${DOWNLOADDIR:-./downloads}:/downloads"
