// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/protobuf/response.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResult_Action int32

const (
	ErrorResult_DEFAULT        ErrorResult_Action = 0
	ErrorResult_UNAUTHORIZED   ErrorResult_Action = 1
	ErrorResult_MAINTENANCE    ErrorResult_Action = 2
	ErrorResult_GEOIP_BLOCKING ErrorResult_Action = 3
)

// Enum value maps for ErrorResult_Action.
var (
	ErrorResult_Action_name = map[int32]string{
		0: "DEFAULT",
		1: "UNAUTHORIZED",
		2: "MAINTENANCE",
		3: "GEOIP_BLOCKING",
	}
	ErrorResult_Action_value = map[string]int32{
		"DEFAULT":        0,
		"UNAUTHORIZED":   1,
		"MAINTENANCE":    2,
		"GEOIP_BLOCKING": 3,
	}
)

func (x ErrorResult_Action) Enum() *ErrorResult_Action {
	p := new(ErrorResult_Action)
	*p = x
	return p
}

func (x ErrorResult_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResult_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protobuf_response_proto_enumTypes[0].Descriptor()
}

func (ErrorResult_Action) Type() protoreflect.EnumType {
	return &file_internal_protobuf_response_proto_enumTypes[0]
}

func (x ErrorResult_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorResult_Action.Descriptor instead.
func (ErrorResult_Action) EnumDescriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{8, 0}
}

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Action        *TransitionAction      `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_internal_protobuf_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Banner) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Banner) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BannerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerTitle   string                 `protobuf:"bytes,1,opt,name=banner_title,json=bannerTitle,proto3" json:"banner_title,omitempty"`
	Banners       []*Banner              `protobuf:"bytes,2,rep,name=banners,proto3" json:"banners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerList) Reset() {
	*x = BannerList{}
	mi := &file_internal_protobuf_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerList) ProtoMessage() {}

func (x *BannerList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerList.ProtoReflect.Descriptor instead.
func (*BannerList) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{1}
}

func (x *BannerList) GetBannerTitle() string {
	if x != nil {
		return x.BannerTitle
	}
	return ""
}

func (x *BannerList) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

type TransitionAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        int32                  `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionAction) Reset() {
	*x = TransitionAction{}
	mi := &file_internal_protobuf_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionAction) ProtoMessage() {}

func (x *TransitionAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionAction.ProtoReflect.Descriptor instead.
func (*TransitionAction) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{2}
}

func (x *TransitionAction) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *TransitionAction) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Chapter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TitleId        uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	ChapterId      uint32                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SubTitle       string                 `protobuf:"bytes,4,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	ThumbnailUrl   string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	StartTimestamp uint32                 `protobuf:"varint,6,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   uint32                 `protobuf:"varint,7,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	AlreadyViewed  bool                   `protobuf:"varint,8,opt,name=already_viewed,json=alreadyViewed,proto3" json:"already_viewed,omitempty"`
	IsVerticalOnly bool                   `protobuf:"varint,9,opt,name=is_vertical_only,json=isVerticalOnly,proto3" json:"is_vertical_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_internal_protobuf_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{3}
}

func (x *Chapter) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Chapter) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *Chapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chapter) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *Chapter) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Chapter) GetStartTimestamp() uint32 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *Chapter) GetEndTimestamp() uint32 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *Chapter) GetAlreadyViewed() bool {
	if x != nil {
		return x.AlreadyViewed
	}
	return false
}

func (x *Chapter) GetIsVerticalOnly() bool {
	if x != nil {
		return x.IsVerticalOnly
	}
	return false
}

type ChapterGroup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChapterNumbers   string                 `protobuf:"bytes,1,opt,name=chapter_numbers,json=chapterNumbers,proto3" json:"chapter_numbers,omitempty"`
	FirstChapterList []*Chapter             `protobuf:"bytes,2,rep,name=first_chapter_list,json=firstChapterList,proto3" json:"first_chapter_list,omitempty"`
	MidChapterList   []*Chapter             `protobuf:"bytes,3,rep,name=mid_chapter_list,json=midChapterList,proto3" json:"mid_chapter_list,omitempty"`
	LastChapterList  []*Chapter             `protobuf:"bytes,4,rep,name=last_chapter_list,json=lastChapterList,proto3" json:"last_chapter_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChapterGroup) Reset() {
	*x = ChapterGroup{}
	mi := &file_internal_protobuf_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterGroup) ProtoMessage() {}

func (x *ChapterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterGroup.ProtoReflect.Descriptor instead.
func (*ChapterGroup) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{4}
}

func (x *ChapterGroup) GetChapterNumbers() string {
	if x != nil {
		return x.ChapterNumbers
	}
	return ""
}

func (x *ChapterGroup) GetFirstChapterList() []*Chapter {
	if x != nil {
		return x.FirstChapterList
	}
	return nil
}

func (x *ChapterGroup) GetMidChapterList() []*Chapter {
	if x != nil {
		return x.MidChapterList
	}
	return nil
}

func (x *ChapterGroup) GetLastChapterList() []*Chapter {
	if x != nil {
		return x.LastChapterList
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsMyComment   bool                   `protobuf:"varint,6,opt,name=is_my_comment,json=isMyComment,proto3" json:"is_my_comment,omitempty"`
	AlreadyLiked  bool                   `protobuf:"varint,7,opt,name=already_liked,json=alreadyLiked,proto3" json:"already_liked,omitempty"`
	NumberOfLikes uint32                 `protobuf:"varint,9,opt,name=number_of_likes,json=numberOfLikes,proto3" json:"number_of_likes,omitempty"`
	Body          string                 `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	Created       uint32                 `protobuf:"varint,11,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_internal_protobuf_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{5}
}

func (x *Comment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Comment) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Comment) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Comment) GetIsMyComment() bool {
	if x != nil {
		return x.IsMyComment
	}
	return false
}

func (x *Comment) GetAlreadyLiked() bool {
	if x != nil {
		return x.AlreadyLiked
	}
	return false
}

func (x *Comment) GetNumberOfLikes() uint32 {
	if x != nil {
		return x.NumberOfLikes
	}
	return 0
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetCreated() uint32 {
	if x != nil {
		return x.Created
	}
	return 0
}

type AdNetworkList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	AdNetworks    *AdNetworkList_AdNetwork `protobuf:"bytes,1,opt,name=ad_networks,json=adNetworks,proto3" json:"ad_networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdNetworkList) Reset() {
	*x = AdNetworkList{}
	mi := &file_internal_protobuf_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdNetworkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdNetworkList) ProtoMessage() {}

func (x *AdNetworkList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdNetworkList.ProtoReflect.Descriptor instead.
func (*AdNetworkList) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{6}
}

func (x *AdNetworkList) GetAdNetworks() *AdNetworkList_AdNetwork {
	if x != nil {
		return x.AdNetworks
	}
	return nil
}

type Popup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OsDefault     *Popup_OSDefault       `protobuf:"bytes,1,opt,name=os_default,json=osDefault,proto3" json:"os_default,omitempty"`
	AppDefault    *Popup_AppDefault      `protobuf:"bytes,2,opt,name=app_default,json=appDefault,proto3" json:"app_default,omitempty"`
	MovieReward   *Popup_MovieReward     `protobuf:"bytes,3,opt,name=movie_reward,json=movieReward,proto3" json:"movie_reward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup) Reset() {
	*x = Popup{}
	mi := &file_internal_protobuf_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup) ProtoMessage() {}

func (x *Popup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup.ProtoReflect.Descriptor instead.
func (*Popup) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{7}
}

func (x *Popup) GetOsDefault() *Popup_OSDefault {
	if x != nil {
		return x.OsDefault
	}
	return nil
}

func (x *Popup) GetAppDefault() *Popup_AppDefault {
	if x != nil {
		return x.AppDefault
	}
	return nil
}

func (x *Popup) GetMovieReward() *Popup_MovieReward {
	if x != nil {
		return x.MovieReward
	}
	return nil
}

type ErrorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        ErrorResult_Action     `protobuf:"varint,1,opt,name=action,proto3,enum=protobuf.ErrorResult_Action" json:"action,omitempty"`
	EnglishPopup  *Popup_OSDefault       `protobuf:"bytes,2,opt,name=english_popup,json=englishPopup,proto3" json:"english_popup,omitempty"`
	SpanishPopup  *Popup_OSDefault       `protobuf:"bytes,3,opt,name=spanish_popup,json=spanishPopup,proto3" json:"spanish_popup,omitempty"`
	DebugInfo     string                 `protobuf:"bytes,4,opt,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty"`
	Popups        []*Popup_OSDefault     `protobuf:"bytes,5,rep,name=popups,proto3" json:"popups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResult) Reset() {
	*x = ErrorResult{}
	mi := &file_internal_protobuf_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResult) ProtoMessage() {}

func (x *ErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResult.ProtoReflect.Descriptor instead.
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResult) GetAction() ErrorResult_Action {
	if x != nil {
		return x.Action
	}
	return ErrorResult_DEFAULT
}

func (x *ErrorResult) GetEnglishPopup() *Popup_OSDefault {
	if x != nil {
		return x.EnglishPopup
	}
	return nil
}

func (x *ErrorResult) GetSpanishPopup() *Popup_OSDefault {
	if x != nil {
		return x.SpanishPopup
	}
	return nil
}

func (x *ErrorResult) GetDebugInfo() string {
	if x != nil {
		return x.DebugInfo
	}
	return ""
}

func (x *ErrorResult) GetPopups() []*Popup_OSDefault {
	if x != nil {
		return x.Popups
	}
	return nil
}

type RegistrationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceSecret  string                 `protobuf:"bytes,1,opt,name=device_secret,json=deviceSecret,proto3" json:"device_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationData) Reset() {
	*x = RegistrationData{}
	mi := &file_internal_protobuf_response_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationData) ProtoMessage() {}

func (x *RegistrationData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationData.ProtoReflect.Descriptor instead.
func (*RegistrationData) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{9}
}

func (x *RegistrationData) GetDeviceSecret() string {
	if x != nil {
		return x.DeviceSecret
	}
	return ""
}

type LastPage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentChapter *Chapter               `protobuf:"bytes,1,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	NextChapter    *Chapter               `protobuf:"bytes,2,opt,name=next_chapter,json=nextChapter,proto3" json:"next_chapter,omitempty"`
	TopComments    []*Comment             `protobuf:"bytes,3,rep,name=top_comments,json=topComments,proto3" json:"top_comments,omitempty"`
	IsSubscribed   bool                   `protobuf:"varint,4,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	NextTimestamp  uint32                 `protobuf:"varint,5,opt,name=next_timestamp,json=nextTimestamp,proto3" json:"next_timestamp,omitempty"`
	ChapterType    int32                  `protobuf:"varint,6,opt,name=chapter_type,json=chapterType,proto3" json:"chapter_type,omitempty"`
	Advertisement  *AdNetworkList         `protobuf:"bytes,7,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	MovieReward    *Popup                 `protobuf:"bytes,8,opt,name=movie_reward,json=movieReward,proto3" json:"movie_reward,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LastPage) Reset() {
	*x = LastPage{}
	mi := &file_internal_protobuf_response_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastPage) ProtoMessage() {}

func (x *LastPage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastPage.ProtoReflect.Descriptor instead.
func (*LastPage) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{10}
}

func (x *LastPage) GetCurrentChapter() *Chapter {
	if x != nil {
		return x.CurrentChapter
	}
	return nil
}

func (x *LastPage) GetNextChapter() *Chapter {
	if x != nil {
		return x.NextChapter
	}
	return nil
}

func (x *LastPage) GetTopComments() []*Comment {
	if x != nil {
		return x.TopComments
	}
	return nil
}

func (x *LastPage) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *LastPage) GetNextTimestamp() uint32 {
	if x != nil {
		return x.NextTimestamp
	}
	return 0
}

func (x *LastPage) GetChapterType() int32 {
	if x != nil {
		return x.ChapterType
	}
	return 0
}

func (x *LastPage) GetAdvertisement() *AdNetworkList {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

func (x *LastPage) GetMovieReward() *Popup {
	if x != nil {
		return x.MovieReward
	}
	return nil
}

// MangaPage
type MangaPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	EncryptionKey string                 `protobuf:"bytes,5,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaPage) Reset() {
	*x = MangaPage{}
	mi := &file_internal_protobuf_response_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaPage) ProtoMessage() {}

func (x *MangaPage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaPage.ProtoReflect.Descriptor instead.
func (*MangaPage) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{11}
}

func (x *MangaPage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MangaPage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MangaPage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MangaPage) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MangaPage) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

// Page
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaPage     *MangaPage             `protobuf:"bytes,1,opt,name=manga_page,json=mangaPage,proto3" json:"manga_page,omitempty"`
	BannerList    *BannerList            `protobuf:"bytes,2,opt,name=banner_list,json=bannerList,proto3" json:"banner_list,omitempty"`
	LastPage      *LastPage              `protobuf:"bytes,3,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	Advertisement *AdNetworkList         `protobuf:"bytes,4,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_internal_protobuf_response_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{12}
}

func (x *Page) GetMangaPage() *MangaPage {
	if x != nil {
		return x.MangaPage
	}
	return nil
}

func (x *Page) GetBannerList() *BannerList {
	if x != nil {
		return x.BannerList
	}
	return nil
}

func (x *Page) GetLastPage() *LastPage {
	if x != nil {
		return x.LastPage
	}
	return nil
}

func (x *Page) GetAdvertisement() *AdNetworkList {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

type Sns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sns) Reset() {
	*x = Sns{}
	mi := &file_internal_protobuf_response_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sns) ProtoMessage() {}

func (x *Sns) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sns.ProtoReflect.Descriptor instead.
func (*Sns) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{13}
}

func (x *Sns) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Sns) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// MangaViewer
type MangaViewer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pages            []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	ChapterId        uint32                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Chapters         []*Chapter             `protobuf:"bytes,3,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Sns              *Sns                   `protobuf:"bytes,4,opt,name=sns,proto3" json:"sns,omitempty"`
	TitleName        string                 `protobuf:"bytes,5,opt,name=title_name,json=titleName,proto3" json:"title_name,omitempty"`
	ChapterName      string                 `protobuf:"bytes,6,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	NumberOfComments uint32                 `protobuf:"varint,7,opt,name=number_of_comments,json=numberOfComments,proto3" json:"number_of_comments,omitempty"`
	IsVerticalOnly   bool                   `protobuf:"varint,8,opt,name=is_vertical_only,json=isVerticalOnly,proto3" json:"is_vertical_only,omitempty"`
	TitleId          uint32                 `protobuf:"varint,9,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	StartFromRight   bool                   `protobuf:"varint,10,opt,name=start_from_right,json=startFromRight,proto3" json:"start_from_right,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MangaViewer) Reset() {
	*x = MangaViewer{}
	mi := &file_internal_protobuf_response_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaViewer) ProtoMessage() {}

func (x *MangaViewer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaViewer.ProtoReflect.Descriptor instead.
func (*MangaViewer) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{14}
}

func (x *MangaViewer) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *MangaViewer) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *MangaViewer) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *MangaViewer) GetSns() *Sns {
	if x != nil {
		return x.Sns
	}
	return nil
}

func (x *MangaViewer) GetTitleName() string {
	if x != nil {
		return x.TitleName
	}
	return ""
}

func (x *MangaViewer) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *MangaViewer) GetNumberOfComments() uint32 {
	if x != nil {
		return x.NumberOfComments
	}
	return 0
}

func (x *MangaViewer) GetIsVerticalOnly() bool {
	if x != nil {
		return x.IsVerticalOnly
	}
	return false
}

func (x *MangaViewer) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *MangaViewer) GetStartFromRight() bool {
	if x != nil {
		return x.StartFromRight
	}
	return false
}

type Title struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TitleId           uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author            string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	PortraitImageUrl  string                 `protobuf:"bytes,4,opt,name=portrait_image_url,json=portraitImageUrl,proto3" json:"portrait_image_url,omitempty"`
	LandscapeImageUrl string                 `protobuf:"bytes,5,opt,name=landscape_image_url,json=landscapeImageUrl,proto3" json:"landscape_image_url,omitempty"`
	ViewCount         uint32                 `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Language          int32                  `protobuf:"varint,7,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_internal_protobuf_response_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{15}
}

func (x *Title) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Title) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Title) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Title) GetPortraitImageUrl() string {
	if x != nil {
		return x.PortraitImageUrl
	}
	return ""
}

func (x *Title) GetLandscapeImageUrl() string {
	if x != nil {
		return x.LandscapeImageUrl
	}
	return ""
}

func (x *Title) GetViewCount() uint32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Title) GetLanguage() int32 {
	if x != nil {
		return x.Language
	}
	return 0
}

type TitleDetailView struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Title                    *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleImageUrl            string                 `protobuf:"bytes,2,opt,name=title_image_url,json=titleImageUrl,proto3" json:"title_image_url,omitempty"`
	Overview                 string                 `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	BackgroundImageUrl       string                 `protobuf:"bytes,4,opt,name=background_image_url,json=backgroundImageUrl,proto3" json:"background_image_url,omitempty"`
	NextTimestamp            uint32                 `protobuf:"varint,5,opt,name=next_timestamp,json=nextTimestamp,proto3" json:"next_timestamp,omitempty"`
	UpdateTiming             int32                  `protobuf:"varint,6,opt,name=update_timing,json=updateTiming,proto3" json:"update_timing,omitempty"`
	ViewingPeriodDescription string                 `protobuf:"bytes,7,opt,name=viewing_period_description,json=viewingPeriodDescription,proto3" json:"viewing_period_description,omitempty"`
	NonAppearanceInfo        string                 `protobuf:"bytes,8,opt,name=non_appearance_info,json=nonAppearanceInfo,proto3" json:"non_appearance_info,omitempty"`
	FirstChapterList         []*Chapter             `protobuf:"bytes,9,rep,name=first_chapter_list,json=firstChapterList,proto3" json:"first_chapter_list,omitempty"`
	LastChapterList          []*Chapter             `protobuf:"bytes,10,rep,name=last_chapter_list,json=lastChapterList,proto3" json:"last_chapter_list,omitempty"`
	Banners                  []*Banner              `protobuf:"bytes,11,rep,name=banners,proto3" json:"banners,omitempty"`
	RecommendedTitleList     []*Title               `protobuf:"bytes,12,rep,name=recommended_title_list,json=recommendedTitleList,proto3" json:"recommended_title_list,omitempty"`
	Sns                      *Sns                   `protobuf:"bytes,13,opt,name=sns,proto3" json:"sns,omitempty"`
	IsSimulReleased          bool                   `protobuf:"varint,14,opt,name=is_simul_released,json=isSimulReleased,proto3" json:"is_simul_released,omitempty"`
	IsSubscribed             bool                   `protobuf:"varint,15,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	Rating                   int32                  `protobuf:"varint,16,opt,name=rating,proto3" json:"rating,omitempty"`
	ChaptersDescending       bool                   `protobuf:"varint,17,opt,name=chapters_descending,json=chaptersDescending,proto3" json:"chapters_descending,omitempty"`
	NumberOfViews            uint32                 `protobuf:"varint,18,opt,name=number_of_views,json=numberOfViews,proto3" json:"number_of_views,omitempty"`
	ChapterListGroup         []*ChapterGroup        `protobuf:"bytes,28,rep,name=chapter_list_group,json=chapterListGroup,proto3" json:"chapter_list_group,omitempty"`
	ChapterListV2            []*Chapter             `protobuf:"bytes,38,rep,name=chapter_list_v2,json=chapterListV2,proto3" json:"chapter_list_v2,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TitleDetailView) Reset() {
	*x = TitleDetailView{}
	mi := &file_internal_protobuf_response_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView) ProtoMessage() {}

func (x *TitleDetailView) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView.ProtoReflect.Descriptor instead.
func (*TitleDetailView) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{16}
}

func (x *TitleDetailView) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TitleDetailView) GetTitleImageUrl() string {
	if x != nil {
		return x.TitleImageUrl
	}
	return ""
}

func (x *TitleDetailView) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *TitleDetailView) GetBackgroundImageUrl() string {
	if x != nil {
		return x.BackgroundImageUrl
	}
	return ""
}

func (x *TitleDetailView) GetNextTimestamp() uint32 {
	if x != nil {
		return x.NextTimestamp
	}
	return 0
}

func (x *TitleDetailView) GetUpdateTiming() int32 {
	if x != nil {
		return x.UpdateTiming
	}
	return 0
}

func (x *TitleDetailView) GetViewingPeriodDescription() string {
	if x != nil {
		return x.ViewingPeriodDescription
	}
	return ""
}

func (x *TitleDetailView) GetNonAppearanceInfo() string {
	if x != nil {
		return x.NonAppearanceInfo
	}
	return ""
}

func (x *TitleDetailView) GetFirstChapterList() []*Chapter {
	if x != nil {
		return x.FirstChapterList
	}
	return nil
}

func (x *TitleDetailView) GetLastChapterList() []*Chapter {
	if x != nil {
		return x.LastChapterList
	}
	return nil
}

func (x *TitleDetailView) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

func (x *TitleDetailView) GetRecommendedTitleList() []*Title {
	if x != nil {
		return x.RecommendedTitleList
	}
	return nil
}

func (x *TitleDetailView) GetSns() *Sns {
	if x != nil {
		return x.Sns
	}
	return nil
}

func (x *TitleDetailView) GetIsSimulReleased() bool {
	if x != nil {
		return x.IsSimulReleased
	}
	return false
}

func (x *TitleDetailView) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *TitleDetailView) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *TitleDetailView) GetChaptersDescending() bool {
	if x != nil {
		return x.ChaptersDescending
	}
	return false
}

func (x *TitleDetailView) GetNumberOfViews() uint32 {
	if x != nil {
		return x.NumberOfViews
	}
	return 0
}

func (x *TitleDetailView) GetChapterListGroup() []*ChapterGroup {
	if x != nil {
		return x.ChapterListGroup
	}
	return nil
}

func (x *TitleDetailView) GetChapterListV2() []*Chapter {
	if x != nil {
		return x.ChapterListV2
	}
	return nil
}

type SuccessResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegisterationData *RegistrationData      `protobuf:"bytes,2,opt,name=registeration_data,json=registerationData,proto3" json:"registeration_data,omitempty"`
	TitleDetailView   *TitleDetailView       `protobuf:"bytes,8,opt,name=title_detail_view,json=titleDetailView,proto3" json:"title_detail_view,omitempty"`
	MangaViewer       *MangaViewer           `protobuf:"bytes,10,opt,name=manga_viewer,json=mangaViewer,proto3" json:"manga_viewer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuccessResult) Reset() {
	*x = SuccessResult{}
	mi := &file_internal_protobuf_response_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResult) ProtoMessage() {}

func (x *SuccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResult.ProtoReflect.Descriptor instead.
func (*SuccessResult) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{17}
}

func (x *SuccessResult) GetRegisterationData() *RegistrationData {
	if x != nil {
		return x.RegisterationData
	}
	return nil
}

func (x *SuccessResult) GetTitleDetailView() *TitleDetailView {
	if x != nil {
		return x.TitleDetailView
	}
	return nil
}

func (x *SuccessResult) GetMangaViewer() *MangaViewer {
	if x != nil {
		return x.MangaViewer
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *SuccessResult         `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *ErrorResult           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_protobuf_response_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{18}
}

func (x *Response) GetSuccess() *SuccessResult {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *Response) GetError() *ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

type AdNetworkList_AdNetwork struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Facebook      *AdNetworkList_AdNetwork_Facebook `protobuf:"bytes,1,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Admob         *AdNetworkList_AdNetwork_Admob    `protobuf:"bytes,2,opt,name=admob,proto3" json:"admob,omitempty"`
	Mopub         *AdNetworkList_AdNetwork_Mopub    `protobuf:"bytes,3,opt,name=mopub,proto3" json:"mopub,omitempty"`
	Adsense       *AdNetworkList_AdNetwork_Adsense  `protobuf:"bytes,4,opt,name=adsense,proto3" json:"adsense,omitempty"`
	Applovin      *AdNetworkList_AdNetwork_Applovin `protobuf:"bytes,5,opt,name=applovin,proto3" json:"applovin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdNetworkList_AdNetwork) Reset() {
	*x = AdNetworkList_AdNetwork{}
	mi := &file_internal_protobuf_response_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdNetworkList_AdNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdNetworkList_AdNetwork) ProtoMessage() {}

func (x *AdNetworkList_AdNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdNetworkList_AdNetwork.ProtoReflect.Descriptor instead.
func (*AdNetworkList_AdNetwork) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{6, 0}
}

func (x *AdNetworkList_AdNetwork) GetFacebook() *AdNetworkList_AdNetwork_Facebook {
	if x != nil {
		return x.Facebook
	}
	return nil
}

func (x *AdNetworkList_AdNetwork) GetAdmob() *AdNetworkList_AdNetwork_Admob {
	if x != nil {
		return x.Admob
	}
	return nil
}

func (x *AdNetworkList_AdNetwork) GetMopub() *AdNetworkList_AdNetwork_Mopub {
	if x != nil {
		return x.Mopub
	}
	return nil
}

func (x *AdNetworkList_AdNetwork) GetAdsense() *AdNetworkList_AdNetwork_Adsense {
	if x != nil {
		return x.Adsense
	}
	return nil
}

func (x *AdNetworkList_AdNetwork) GetApplovin() *AdNetworkList_AdNetwork_Applovin {
	if x != nil {
		return x.Applovin
	}
	return nil
}

type AdNetworkList_AdNetwork_Facebook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlacementId   string                 `protobuf:"bytes,1,opt,name=placement_id,json=placementId,proto3" json:"placement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdNetworkList_AdNetwork_Facebook) Reset() {
	*x = AdNetworkList_AdNetwork_Facebook{}
	mi := &file_internal_protobuf_response_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdNetworkList_AdNetwork_Facebook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdNetworkList_AdNetwork_Facebook) ProtoMessage() {}

func (x *AdNetworkList_AdNetwork_Facebook) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdNetworkList_AdNetwork_Facebook.ProtoReflect.Descriptor instead.
func (*AdNetworkList_AdNetwork_Facebook) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *AdNetworkList_AdNetwork_Facebook) GetPlacementId() string {
	if x != nil {
		return x.PlacementId
	}
	return ""
}

type AdNetworkList_AdNetwork_Admob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdNetworkList_AdNetwork_Admob) Reset() {
	*x = AdNetworkList_AdNetwork_Admob{}
	mi := &file_internal_protobuf_response_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdNetworkList_AdNetwork_Admob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdNetworkList_AdNetwork_Admob) ProtoMessage() {}

func (x *AdNetworkList_AdNetwork_Admob) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdNetworkList_AdNetwork_Admob.ProtoReflect.Descriptor instead.
func (*AdNetworkList_AdNetwork_Admob) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{6, 0, 1}
}

func (x *AdNetworkList_AdNetwork_Admob) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type AdNetworkList_AdNetwork_Mopub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdNetworkList_AdNetwork_Mopub) Reset() {
	*x = AdNetworkList_AdNetwork_Mopub{}
	mi := &file_internal_protobuf_response_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdNetworkList_AdNetwork_Mopub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdNetworkList_AdNetwork_Mopub) ProtoMessage() {}

func (x *AdNetworkList_AdNetwork_Mopub) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdNetworkList_AdNetwork_Mopub.ProtoReflect.Descriptor instead.
func (*AdNetworkList_AdNetwork_Mopub) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{6, 0, 2}
}

func (x *AdNetworkList_AdNetwork_Mopub) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type AdNetworkList_AdNetwork_Adsense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdNetworkList_AdNetwork_Adsense) Reset() {
	*x = AdNetworkList_AdNetwork_Adsense{}
	mi := &file_internal_protobuf_response_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdNetworkList_AdNetwork_Adsense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdNetworkList_AdNetwork_Adsense) ProtoMessage() {}

func (x *AdNetworkList_AdNetwork_Adsense) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdNetworkList_AdNetwork_Adsense.ProtoReflect.Descriptor instead.
func (*AdNetworkList_AdNetwork_Adsense) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{6, 0, 3}
}

func (x *AdNetworkList_AdNetwork_Adsense) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type AdNetworkList_AdNetwork_Applovin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdNetworkList_AdNetwork_Applovin) Reset() {
	*x = AdNetworkList_AdNetwork_Applovin{}
	mi := &file_internal_protobuf_response_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdNetworkList_AdNetwork_Applovin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdNetworkList_AdNetwork_Applovin) ProtoMessage() {}

func (x *AdNetworkList_AdNetwork_Applovin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdNetworkList_AdNetwork_Applovin.ProtoReflect.Descriptor instead.
func (*AdNetworkList_AdNetwork_Applovin) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{6, 0, 4}
}

func (x *AdNetworkList_AdNetwork_Applovin) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type Popup_Button struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Action        *TransitionAction      `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_Button) Reset() {
	*x = Popup_Button{}
	mi := &file_internal_protobuf_response_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_Button) ProtoMessage() {}

func (x *Popup_Button) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_Button.ProtoReflect.Descriptor instead.
func (*Popup_Button) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Popup_Button) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Popup_Button) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type Popup_OSDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	OkButton      *Popup_Button          `protobuf:"bytes,3,opt,name=ok_button,json=okButton,proto3" json:"ok_button,omitempty"`
	NeutralButton *Popup_Button          `protobuf:"bytes,4,opt,name=neutral_button,json=neutralButton,proto3" json:"neutral_button,omitempty"`
	CancelButton  *Popup_Button          `protobuf:"bytes,5,opt,name=cancel_button,json=cancelButton,proto3" json:"cancel_button,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_OSDefault) Reset() {
	*x = Popup_OSDefault{}
	mi := &file_internal_protobuf_response_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_OSDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_OSDefault) ProtoMessage() {}

func (x *Popup_OSDefault) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_OSDefault.ProtoReflect.Descriptor instead.
func (*Popup_OSDefault) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{7, 1}
}

func (x *Popup_OSDefault) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Popup_OSDefault) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Popup_OSDefault) GetOkButton() *Popup_Button {
	if x != nil {
		return x.OkButton
	}
	return nil
}

func (x *Popup_OSDefault) GetNeutralButton() *Popup_Button {
	if x != nil {
		return x.NeutralButton
	}
	return nil
}

func (x *Popup_OSDefault) GetCancelButton() *Popup_Button {
	if x != nil {
		return x.CancelButton
	}
	return nil
}

type Popup_AppDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Action        *TransitionAction      `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_AppDefault) Reset() {
	*x = Popup_AppDefault{}
	mi := &file_internal_protobuf_response_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_AppDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_AppDefault) ProtoMessage() {}

func (x *Popup_AppDefault) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_AppDefault.ProtoReflect.Descriptor instead.
func (*Popup_AppDefault) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{7, 2}
}

func (x *Popup_AppDefault) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Popup_AppDefault) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Popup_AppDefault) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Popup_AppDefault) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type Popup_MovieReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Advertisement *AdNetworkList         `protobuf:"bytes,2,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_MovieReward) Reset() {
	*x = Popup_MovieReward{}
	mi := &file_internal_protobuf_response_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_MovieReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_MovieReward) ProtoMessage() {}

func (x *Popup_MovieReward) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_response_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_MovieReward.ProtoReflect.Descriptor instead.
func (*Popup_MovieReward) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_response_proto_rawDescGZIP(), []int{7, 3}
}

func (x *Popup_MovieReward) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Popup_MovieReward) GetAdvertisement() *AdNetworkList {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

var File_internal_protobuf_response_proto protoreflect.FileDescriptor

const file_internal_protobuf_response_proto_rawDesc = "" +
	"\n" +
	" internal/protobuf/response.proto\x12\bprotobuf\"i\n" +
	"\x06Banner\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x122\n" +
	"\x06action\x18\x02 \x01(\v2\x1a.protobuf.TransitionActionR\x06action\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\"[\n" +
	"\n" +
	"BannerList\x12!\n" +
	"\fbanner_title\x18\x01 \x01(\tR\vbannerTitle\x12*\n" +
	"\abanners\x18\x02 \x03(\v2\x10.protobuf.BannerR\abanners\"<\n" +
	"\x10TransitionAction\x12\x16\n" +
	"\x06method\x18\x01 \x01(\x05R\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xb8\x02\n" +
	"\aChapter\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\rR\tchapterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tsub_title\x18\x04 \x01(\tR\bsubTitle\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12'\n" +
	"\x0fstart_timestamp\x18\x06 \x01(\rR\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\a \x01(\rR\fendTimestamp\x12%\n" +
	"\x0ealready_viewed\x18\b \x01(\bR\ralreadyViewed\x12(\n" +
	"\x10is_vertical_only\x18\t \x01(\bR\x0eisVerticalOnly\"\xf4\x01\n" +
	"\fChapterGroup\x12'\n" +
	"\x0fchapter_numbers\x18\x01 \x01(\tR\x0echapterNumbers\x12?\n" +
	"\x12first_chapter_list\x18\x02 \x03(\v2\x11.protobuf.ChapterR\x10firstChapterList\x12;\n" +
	"\x10mid_chapter_list\x18\x03 \x03(\v2\x11.protobuf.ChapterR\x0emidChapterList\x12=\n" +
	"\x11last_chapter_list\x18\x04 \x03(\v2\x11.protobuf.ChapterR\x0flastChapterList\"\x86\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\x12\"\n" +
	"\ris_my_comment\x18\x06 \x01(\bR\visMyComment\x12#\n" +
	"\ralready_liked\x18\a \x01(\bR\falreadyLiked\x12&\n" +
	"\x0fnumber_of_likes\x18\t \x01(\rR\rnumberOfLikes\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\tR\x04body\x12\x18\n" +
	"\acreated\x18\v \x01(\rR\acreated\"\xf0\x04\n" +
	"\rAdNetworkList\x12B\n" +
	"\vad_networks\x18\x01 \x01(\v2!.protobuf.AdNetworkList.AdNetworkR\n" +
	"adNetworks\x1a\x9a\x04\n" +
	"\tAdNetwork\x12F\n" +
	"\bfacebook\x18\x01 \x01(\v2*.protobuf.AdNetworkList.AdNetwork.FacebookR\bfacebook\x12=\n" +
	"\x05admob\x18\x02 \x01(\v2'.protobuf.AdNetworkList.AdNetwork.AdmobR\x05admob\x12=\n" +
	"\x05mopub\x18\x03 \x01(\v2'.protobuf.AdNetworkList.AdNetwork.MopubR\x05mopub\x12C\n" +
	"\aadsense\x18\x04 \x01(\v2).protobuf.AdNetworkList.AdNetwork.AdsenseR\aadsense\x12F\n" +
	"\bapplovin\x18\x05 \x01(\v2*.protobuf.AdNetworkList.AdNetwork.ApplovinR\bapplovin\x1a-\n" +
	"\bFacebook\x12!\n" +
	"\fplacement_id\x18\x01 \x01(\tR\vplacementId\x1a \n" +
	"\x05Admob\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x1a \n" +
	"\x05Mopub\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x1a\"\n" +
	"\aAdsense\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x1a#\n" +
	"\bApplovin\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\"\xf6\x05\n" +
	"\x05Popup\x128\n" +
	"\n" +
	"os_default\x18\x01 \x01(\v2\x19.protobuf.Popup.OSDefaultR\tosDefault\x12;\n" +
	"\vapp_default\x18\x02 \x01(\v2\x1a.protobuf.Popup.AppDefaultR\n" +
	"appDefault\x12>\n" +
	"\fmovie_reward\x18\x03 \x01(\v2\x1b.protobuf.Popup.MovieRewardR\vmovieReward\x1aP\n" +
	"\x06Button\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x122\n" +
	"\x06action\x18\x02 \x01(\v2\x1a.protobuf.TransitionActionR\x06action\x1a\xea\x01\n" +
	"\tOSDefault\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x123\n" +
	"\tok_button\x18\x03 \x01(\v2\x16.protobuf.Popup.ButtonR\bokButton\x12=\n" +
	"\x0eneutral_button\x18\x04 \x01(\v2\x16.protobuf.Popup.ButtonR\rneutralButton\x12;\n" +
	"\rcancel_button\x18\x05 \x01(\v2\x16.protobuf.Popup.ButtonR\fcancelButton\x1a\x8b\x01\n" +
	"\n" +
	"AppDefault\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x122\n" +
	"\x06action\x18\x03 \x01(\v2\x1a.protobuf.TransitionActionR\x06action\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x1ai\n" +
	"\vMovieReward\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12=\n" +
	"\radvertisement\x18\x02 \x01(\v2\x17.protobuf.AdNetworkListR\radvertisement\"\xe3\x02\n" +
	"\vErrorResult\x124\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1c.protobuf.ErrorResult.ActionR\x06action\x12>\n" +
	"\renglish_popup\x18\x02 \x01(\v2\x19.protobuf.Popup.OSDefaultR\fenglishPopup\x12>\n" +
	"\rspanish_popup\x18\x03 \x01(\v2\x19.protobuf.Popup.OSDefaultR\fspanishPopup\x12\x1d\n" +
	"\n" +
	"debug_info\x18\x04 \x01(\tR\tdebugInfo\x121\n" +
	"\x06popups\x18\x05 \x03(\v2\x19.protobuf.Popup.OSDefaultR\x06popups\"L\n" +
	"\x06Action\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x01\x12\x0f\n" +
	"\vMAINTENANCE\x10\x02\x12\x12\n" +
	"\x0eGEOIP_BLOCKING\x10\x03\"7\n" +
	"\x10RegistrationData\x12#\n" +
	"\rdevice_secret\x18\x01 \x01(\tR\fdeviceSecret\"\x94\x03\n" +
	"\bLastPage\x12:\n" +
	"\x0fcurrent_chapter\x18\x01 \x01(\v2\x11.protobuf.ChapterR\x0ecurrentChapter\x124\n" +
	"\fnext_chapter\x18\x02 \x01(\v2\x11.protobuf.ChapterR\vnextChapter\x124\n" +
	"\ftop_comments\x18\x03 \x03(\v2\x11.protobuf.CommentR\vtopComments\x12#\n" +
	"\ris_subscribed\x18\x04 \x01(\bR\fisSubscribed\x12%\n" +
	"\x0enext_timestamp\x18\x05 \x01(\rR\rnextTimestamp\x12!\n" +
	"\fchapter_type\x18\x06 \x01(\x05R\vchapterType\x12=\n" +
	"\radvertisement\x18\a \x01(\v2\x17.protobuf.AdNetworkListR\radvertisement\x122\n" +
	"\fmovie_reward\x18\b \x01(\v2\x0f.protobuf.PopupR\vmovieReward\"\x91\x01\n" +
	"\tMangaPage\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12%\n" +
	"\x0eencryption_key\x18\x05 \x01(\tR\rencryptionKey\"\xe1\x01\n" +
	"\x04Page\x122\n" +
	"\n" +
	"manga_page\x18\x01 \x01(\v2\x13.protobuf.MangaPageR\tmangaPage\x125\n" +
	"\vbanner_list\x18\x02 \x01(\v2\x14.protobuf.BannerListR\n" +
	"bannerList\x12/\n" +
	"\tlast_page\x18\x03 \x01(\v2\x12.protobuf.LastPageR\blastPage\x12=\n" +
	"\radvertisement\x18\x04 \x01(\v2\x17.protobuf.AdNetworkListR\radvertisement\"+\n" +
	"\x03Sns\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x81\x03\n" +
	"\vMangaViewer\x12$\n" +
	"\x05pages\x18\x01 \x03(\v2\x0e.protobuf.PageR\x05pages\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\rR\tchapterId\x12-\n" +
	"\bchapters\x18\x03 \x03(\v2\x11.protobuf.ChapterR\bchapters\x12\x1f\n" +
	"\x03sns\x18\x04 \x01(\v2\r.protobuf.SnsR\x03sns\x12\x1d\n" +
	"\n" +
	"title_name\x18\x05 \x01(\tR\ttitleName\x12!\n" +
	"\fchapter_name\x18\x06 \x01(\tR\vchapterName\x12,\n" +
	"\x12number_of_comments\x18\a \x01(\rR\x10numberOfComments\x12(\n" +
	"\x10is_vertical_only\x18\b \x01(\bR\x0eisVerticalOnly\x12\x19\n" +
	"\btitle_id\x18\t \x01(\rR\atitleId\x12(\n" +
	"\x10start_from_right\x18\n" +
	" \x01(\bR\x0estartFromRight\"\xe7\x01\n" +
	"\x05Title\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12,\n" +
	"\x12portrait_image_url\x18\x04 \x01(\tR\x10portraitImageUrl\x12.\n" +
	"\x13landscape_image_url\x18\x05 \x01(\tR\x11landscapeImageUrl\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\rR\tviewCount\x12\x1a\n" +
	"\blanguage\x18\a \x01(\x05R\blanguage\"\xbf\a\n" +
	"\x0fTitleDetailView\x12%\n" +
	"\x05title\x18\x01 \x01(\v2\x0f.protobuf.TitleR\x05title\x12&\n" +
	"\x0ftitle_image_url\x18\x02 \x01(\tR\rtitleImageUrl\x12\x1a\n" +
	"\boverview\x18\x03 \x01(\tR\boverview\x120\n" +
	"\x14background_image_url\x18\x04 \x01(\tR\x12backgroundImageUrl\x12%\n" +
	"\x0enext_timestamp\x18\x05 \x01(\rR\rnextTimestamp\x12#\n" +
	"\rupdate_timing\x18\x06 \x01(\x05R\fupdateTiming\x12<\n" +
	"\x1aviewing_period_description\x18\a \x01(\tR\x18viewingPeriodDescription\x12.\n" +
	"\x13non_appearance_info\x18\b \x01(\tR\x11nonAppearanceInfo\x12?\n" +
	"\x12first_chapter_list\x18\t \x03(\v2\x11.protobuf.ChapterR\x10firstChapterList\x12=\n" +
	"\x11last_chapter_list\x18\n" +
	" \x03(\v2\x11.protobuf.ChapterR\x0flastChapterList\x12*\n" +
	"\abanners\x18\v \x03(\v2\x10.protobuf.BannerR\abanners\x12E\n" +
	"\x16recommended_title_list\x18\f \x03(\v2\x0f.protobuf.TitleR\x14recommendedTitleList\x12\x1f\n" +
	"\x03sns\x18\r \x01(\v2\r.protobuf.SnsR\x03sns\x12*\n" +
	"\x11is_simul_released\x18\x0e \x01(\bR\x0fisSimulReleased\x12#\n" +
	"\ris_subscribed\x18\x0f \x01(\bR\fisSubscribed\x12\x16\n" +
	"\x06rating\x18\x10 \x01(\x05R\x06rating\x12/\n" +
	"\x13chapters_descending\x18\x11 \x01(\bR\x12chaptersDescending\x12&\n" +
	"\x0fnumber_of_views\x18\x12 \x01(\rR\rnumberOfViews\x12D\n" +
	"\x12chapter_list_group\x18\x1c \x03(\v2\x16.protobuf.ChapterGroupR\x10chapterListGroup\x129\n" +
	"\x0fchapter_list_v2\x18& \x03(\v2\x11.protobuf.ChapterR\rchapterListV2\"\xdb\x01\n" +
	"\rSuccessResult\x12I\n" +
	"\x12registeration_data\x18\x02 \x01(\v2\x1a.protobuf.RegistrationDataR\x11registerationData\x12E\n" +
	"\x11title_detail_view\x18\b \x01(\v2\x19.protobuf.TitleDetailViewR\x0ftitleDetailView\x128\n" +
	"\fmanga_viewer\x18\n" +
	" \x01(\v2\x15.protobuf.MangaViewerR\vmangaViewer\"j\n" +
	"\bResponse\x121\n" +
	"\asuccess\x18\x01 \x01(\v2\x17.protobuf.SuccessResultR\asuccess\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.protobuf.ErrorResultR\x05errorB\x13Z\x11internal/protobufb\x06proto3"

var (
	file_internal_protobuf_response_proto_rawDescOnce sync.Once
	file_internal_protobuf_response_proto_rawDescData []byte
)

func file_internal_protobuf_response_proto_rawDescGZIP() []byte {
	file_internal_protobuf_response_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_response_proto_rawDesc), len(file_internal_protobuf_response_proto_rawDesc)))
	})
	return file_internal_protobuf_response_proto_rawDescData
}

var (
	file_internal_protobuf_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_internal_protobuf_response_proto_msgTypes  = make([]protoimpl.MessageInfo, 29)
	file_internal_protobuf_response_proto_goTypes   = []any{
		(ErrorResult_Action)(0),                  // 0: protobuf.ErrorResult.Action
		(*Banner)(nil),                           // 1: protobuf.Banner
		(*BannerList)(nil),                       // 2: protobuf.BannerList
		(*TransitionAction)(nil),                 // 3: protobuf.TransitionAction
		(*Chapter)(nil),                          // 4: protobuf.Chapter
		(*ChapterGroup)(nil),                     // 5: protobuf.ChapterGroup
		(*Comment)(nil),                          // 6: protobuf.Comment
		(*AdNetworkList)(nil),                    // 7: protobuf.AdNetworkList
		(*Popup)(nil),                            // 8: protobuf.Popup
		(*ErrorResult)(nil),                      // 9: protobuf.ErrorResult
		(*RegistrationData)(nil),                 // 10: protobuf.RegistrationData
		(*LastPage)(nil),                         // 11: protobuf.LastPage
		(*MangaPage)(nil),                        // 12: protobuf.MangaPage
		(*Page)(nil),                             // 13: protobuf.Page
		(*Sns)(nil),                              // 14: protobuf.Sns
		(*MangaViewer)(nil),                      // 15: protobuf.MangaViewer
		(*Title)(nil),                            // 16: protobuf.Title
		(*TitleDetailView)(nil),                  // 17: protobuf.TitleDetailView
		(*SuccessResult)(nil),                    // 18: protobuf.SuccessResult
		(*Response)(nil),                         // 19: protobuf.Response
		(*AdNetworkList_AdNetwork)(nil),          // 20: protobuf.AdNetworkList.AdNetwork
		(*AdNetworkList_AdNetwork_Facebook)(nil), // 21: protobuf.AdNetworkList.AdNetwork.Facebook
		(*AdNetworkList_AdNetwork_Admob)(nil),    // 22: protobuf.AdNetworkList.AdNetwork.Admob
		(*AdNetworkList_AdNetwork_Mopub)(nil),    // 23: protobuf.AdNetworkList.AdNetwork.Mopub
		(*AdNetworkList_AdNetwork_Adsense)(nil),  // 24: protobuf.AdNetworkList.AdNetwork.Adsense
		(*AdNetworkList_AdNetwork_Applovin)(nil), // 25: protobuf.AdNetworkList.AdNetwork.Applovin
		(*Popup_Button)(nil),                     // 26: protobuf.Popup.Button
		(*Popup_OSDefault)(nil),                  // 27: protobuf.Popup.OSDefault
		(*Popup_AppDefault)(nil),                 // 28: protobuf.Popup.AppDefault
		(*Popup_MovieReward)(nil),                // 29: protobuf.Popup.MovieReward
	}
)
var file_internal_protobuf_response_proto_depIdxs = []int32{
	3,  // 0: protobuf.Banner.action:type_name -> protobuf.TransitionAction
	1,  // 1: protobuf.BannerList.banners:type_name -> protobuf.Banner
	4,  // 2: protobuf.ChapterGroup.first_chapter_list:type_name -> protobuf.Chapter
	4,  // 3: protobuf.ChapterGroup.mid_chapter_list:type_name -> protobuf.Chapter
	4,  // 4: protobuf.ChapterGroup.last_chapter_list:type_name -> protobuf.Chapter
	20, // 5: protobuf.AdNetworkList.ad_networks:type_name -> protobuf.AdNetworkList.AdNetwork
	27, // 6: protobuf.Popup.os_default:type_name -> protobuf.Popup.OSDefault
	28, // 7: protobuf.Popup.app_default:type_name -> protobuf.Popup.AppDefault
	29, // 8: protobuf.Popup.movie_reward:type_name -> protobuf.Popup.MovieReward
	0,  // 9: protobuf.ErrorResult.action:type_name -> protobuf.ErrorResult.Action
	27, // 10: protobuf.ErrorResult.english_popup:type_name -> protobuf.Popup.OSDefault
	27, // 11: protobuf.ErrorResult.spanish_popup:type_name -> protobuf.Popup.OSDefault
	27, // 12: protobuf.ErrorResult.popups:type_name -> protobuf.Popup.OSDefault
	4,  // 13: protobuf.LastPage.current_chapter:type_name -> protobuf.Chapter
	4,  // 14: protobuf.LastPage.next_chapter:type_name -> protobuf.Chapter
	6,  // 15: protobuf.LastPage.top_comments:type_name -> protobuf.Comment
	7,  // 16: protobuf.LastPage.advertisement:type_name -> protobuf.AdNetworkList
	8,  // 17: protobuf.LastPage.movie_reward:type_name -> protobuf.Popup
	12, // 18: protobuf.Page.manga_page:type_name -> protobuf.MangaPage
	2,  // 19: protobuf.Page.banner_list:type_name -> protobuf.BannerList
	11, // 20: protobuf.Page.last_page:type_name -> protobuf.LastPage
	7,  // 21: protobuf.Page.advertisement:type_name -> protobuf.AdNetworkList
	13, // 22: protobuf.MangaViewer.pages:type_name -> protobuf.Page
	4,  // 23: protobuf.MangaViewer.chapters:type_name -> protobuf.Chapter
	14, // 24: protobuf.MangaViewer.sns:type_name -> protobuf.Sns
	16, // 25: protobuf.TitleDetailView.title:type_name -> protobuf.Title
	4,  // 26: protobuf.TitleDetailView.first_chapter_list:type_name -> protobuf.Chapter
	4,  // 27: protobuf.TitleDetailView.last_chapter_list:type_name -> protobuf.Chapter
	1,  // 28: protobuf.TitleDetailView.banners:type_name -> protobuf.Banner
	16, // 29: protobuf.TitleDetailView.recommended_title_list:type_name -> protobuf.Title
	14, // 30: protobuf.TitleDetailView.sns:type_name -> protobuf.Sns
	5,  // 31: protobuf.TitleDetailView.chapter_list_group:type_name -> protobuf.ChapterGroup
	4,  // 32: protobuf.TitleDetailView.chapter_list_v2:type_name -> protobuf.Chapter
	10, // 33: protobuf.SuccessResult.registeration_data:type_name -> protobuf.RegistrationData
	17, // 34: protobuf.SuccessResult.title_detail_view:type_name -> protobuf.TitleDetailView
	15, // 35: protobuf.SuccessResult.manga_viewer:type_name -> protobuf.MangaViewer
	18, // 36: protobuf.Response.success:type_name -> protobuf.SuccessResult
	9,  // 37: protobuf.Response.error:type_name -> protobuf.ErrorResult
	21, // 38: protobuf.AdNetworkList.AdNetwork.facebook:type_name -> protobuf.AdNetworkList.AdNetwork.Facebook
	22, // 39: protobuf.AdNetworkList.AdNetwork.admob:type_name -> protobuf.AdNetworkList.AdNetwork.Admob
	23, // 40: protobuf.AdNetworkList.AdNetwork.mopub:type_name -> protobuf.AdNetworkList.AdNetwork.Mopub
	24, // 41: protobuf.AdNetworkList.AdNetwork.adsense:type_name -> protobuf.AdNetworkList.AdNetwork.Adsense
	25, // 42: protobuf.AdNetworkList.AdNetwork.applovin:type_name -> protobuf.AdNetworkList.AdNetwork.Applovin
	3,  // 43: protobuf.Popup.Button.action:type_name -> protobuf.TransitionAction
	26, // 44: protobuf.Popup.OSDefault.ok_button:type_name -> protobuf.Popup.Button
	26, // 45: protobuf.Popup.OSDefault.neutral_button:type_name -> protobuf.Popup.Button
	26, // 46: protobuf.Popup.OSDefault.cancel_button:type_name -> protobuf.Popup.Button
	3,  // 47: protobuf.Popup.AppDefault.action:type_name -> protobuf.TransitionAction
	7,  // 48: protobuf.Popup.MovieReward.advertisement:type_name -> protobuf.AdNetworkList
	49, // [49:49] is the sub-list for method output_type
	49, // [49:49] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_internal_protobuf_response_proto_init() }
func file_internal_protobuf_response_proto_init() {
	if File_internal_protobuf_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_response_proto_rawDesc), len(file_internal_protobuf_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protobuf_response_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_response_proto_depIdxs,
		EnumInfos:         file_internal_protobuf_response_proto_enumTypes,
		MessageInfos:      file_internal_protobuf_response_proto_msgTypes,
	}.Build()
	File_internal_protobuf_response_proto = out.File
	file_internal_protobuf_response_proto_goTypes = nil
	file_internal_protobuf_response_proto_depIdxs = nil
}
